### ISSUE TITLE
Automatically deploy 3 small instances as part of Ops Manager deployment

### ISSUE THREAD

**Issue by jayrunkel** [mdg-2018/cloud-manager-quick-launch#6]
As part of the Ops Manager deployment, automatically deploy 3 small instances and install the automation agent on them to make the process completely automated. (Also, set the expire-on tags to match the Ops Manager instance.)

**Comment by graboskyc** [comment]
Will be part of a bigger initiative to allow inputs of api details to use the current CM deployment page to deploy to any CM or OM

**Comment by graboskyc** [comment]
Resolved in latest release
