### ISSUE TITLE
Ansible script doesn't have all dependances for ubuntu 18. 

### ISSUE THREAD

**Issue by alberttwong** [mdg-2018/cloud-manager-quick-launch#8]
Currently in the ansible script.
```
          - libcurl4
          - libgssapi-krb5-2
          - libkrb5-dbg
          - libldap-2.4-2
          - libpci3
          - libsasl2-2
          - snmp
          - openssl
```

should have for 4.4

sudo apt-get install libcurl4 libgssapi-krb5-2 libldap-2.4-2 libwrap0 libsasl2-2 libsasl2-modules libsasl2-modules-gssapi-mit snmp openssl liblzma5

per https://docs.mongodb.com/manual/tutorial/install-mongodb-enterprise-on-ubuntu-tarball/

**Comment by alberttwong** [comment]
for 4.2

sudo apt-get install libcurl4 libgssapi-krb5-2 libkrb5-dbg libldap-2.4-2 libpci3 libsasl2-2 libsasl2-modules libsasl2-modules-gssapi-mit snmp openssl

**Comment by alberttwong** [comment]
https://github.com/mdg-2018/cloud-manager-quick-launch/pull/9

**Comment by alberttwong** [comment]
for 4.0

sudo apt-get install libcurl4 libgssapi-krb5-2 libkrb5-dbg libldap-2.4-2 libpci3 libwrap0 libsasl2-2 libsasl2-modules libsasl2-modules-gssapi-mit libsensors4 snmp openssl

**Comment by graboskyc** [comment]
libsensors4  doesnt exist @alberttwong

**Comment by mdg-2018** [comment]
The AMI we're using is ubuntu 20.04 rather than 18.04, could be some differences in available packages
